---
- name: Install authentik
  hosts: authentik
  roles:
    - name: Proxmox container setup
      role: proxmox
    - role: hifis.toolkit.unattended_upgrades
      unattended_origins_patterns:
        - 'origin=Debian,codename=${distro_codename},label=Debian-Security' # security updates

    - name: Install Authentik with Docker compose
      role: docker
      vars:
        docker_compose_file_path: "/root/authentik"
        docker_compose_content: |
          services:
            postgresql:
              env_file:
              - .env
              environment:
                POSTGRES_DB: ${PG_DB:-authentik}
                POSTGRES_PASSWORD: ${PG_PASS:?database password required}
                POSTGRES_USER: ${PG_USER:-authentik}
              healthcheck:
                interval: 30s
                retries: 5
                start_period: 20s
                test:
                - CMD-SHELL
                - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
                timeout: 5s
              image: docker.io/library/postgres:16-alpine
              restart: unless-stopped
              volumes:
              - database:/var/lib/postgresql/data
            server:
              command: server
              depends_on:
                postgresql:
                  condition: service_healthy
              env_file:
              - .env
              environment:
                AUTHENTIK_POSTGRESQL__HOST: postgresql
                AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
                AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
                AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
                AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
              image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.5.4}
              ports:
              - ${COMPOSE_PORT_HTTP:-9000}:9000
              - ${COMPOSE_PORT_HTTPS:-9443}:9443
              restart: unless-stopped
              shm_size: 512mb
              volumes:
              - ./data:/data
              - ./custom-templates:/templates
            worker:
              command: worker
              depends_on:
                postgresql:
                  condition: service_healthy
              env_file:
              - .env
              environment:
                AUTHENTIK_POSTGRESQL__HOST: postgresql
                AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
                AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
                AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
                AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
              image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.5.4}
              restart: unless-stopped
              shm_size: 512mb
              user: root
              volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - ./data:/data
              - ./certs:/certs
              - ./custom-templates:/templates
          volumes:
            database:
              driver: local
        docker_compose_env: |
          PG_PASS={{ authentik_pg_pass }}
          AUTHENTIK_SECRET_KEY={{ authentik_secret_key }}
          AUTHENTIK_TAG=2026.5.4
          AUTHENTIK_EMAIL__HOST=smtp.mailbox.org
          AUTHENTIK_EMAIL__PORT=465
          AUTHENTIK_EMAIL__USERNAME=kinsteen@mailbox.org
          AUTHENTIK_EMAIL__PASSWORD={{ authentik_email_password }}
          AUTHENTIK_EMAIL__USE_SSL=true
          AUTHENTIK_EMAIL__FROM=auth@francon.eu

    - name: Install backup script
      role: backup
      vars:
        backup_name: authentik
        backup_root: "/root/authentik"
        backup_folders:
          - data/media/
        backup_docker_postgres:
          service: postgresql
          username: authentik
          file: database.sql
        backup_restic_repositories:
          - name: backblaze
            repository_url: s3:https://s3.eu-central-003.backblazeb2.com/tassigny-bucket/authentik
            repository_password: "{{ authentik_restic_password }}"
            env:
              AWS_ACCESS_KEY_ID: "{{ authentik_restic_aws_access_key_id }}"
              AWS_SECRET_ACCESS_KEY: "{{ authentik_restic_aws_secret_access_key }}"
