- name: Install Docker
  hosts: all
  tasks:
    - name: Wait for container to be up
      retries: 30
      ansible.builtin.wait_for_connection:
  roles:
    - role: proxmox
      vars:
        proxmox_setup_container: true
    - role: docker
