---
- name: Install Docker and OpenBao compose
  hosts: openbao
  roles:
    - name: Proxmox container setup
      role: proxmox

    - role: hifis.toolkit.unattended_upgrades
      unattended_origins_patterns:
        - 'origin=Debian,codename=${distro_codename},label=Debian-Security' # security updates

    - name: Install Docker
      role: docker
      vars:
        docker_compose_file_path: "/root/openbao"
        docker_compose_content: |
          services:
            openbao:
              image: openbao/openbao:latest
              container_name: openbao
              restart: unless-stopped
              environment:
                - lol:lol
              volumes:
                - ./config:/openbao/config
              ports:
                - 8200:8200
              env_file:
                - .env
              mem_swappiness: 0

        docker_compose_env: |
          BAO_DEV_ROOT_TOKEN_ID=root
