---
- name: Ensure restic is installed
  ansible.builtin.package:
    name: restic
    state: present

- name: Copy backup script
  ansible.builtin.template:
    src: backup.sh.j2
    dest: "{{ backup_root }}/backup.sh"
    mode: "0600"
    owner: root
    group: root
    trim_blocks: true

- name: Setup backup Cron
  ansible.builtin.cron:
    name: "{{ backup_name }} backup"
    minute: "5"
    hour: "4"
    job: "bash {{ backup_root }}/backup.sh >/dev/null 2>&1"
